import { Box } from "@mui/material";
import Head from "next/head";

const MainLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Hundred Darts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Box
        sx={{
          width: "100vw",
          height: "100%",
          minHeight: "100vh",
        }}
        bgcolor="grey.900"
        color="grey.50"
      >
        {children}
      </Box>
    </>
  );
};

export default MainLayout;
